In [213]:
import json
import pymongo
from pymongo import MongoClient
import pandas as pd
import matplotlib.pyplot as plt

In [214]:

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [215]:
client = pymongo.MongoClient("mongodb+srv://matias:caos@cluster0-qjij4.mongodb.net/dm?retryWrites=true")
db = client.dm

In [216]:
db

Database(MongoClient(host=['cluster0-shard-00-00-qjij4.mongodb.net:27017', 'cluster0-shard-00-01-qjij4.mongodb.net:27017', 'cluster0-shard-00-02-qjij4.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', replicaset='Cluster0-shard-0', ssl=True, retrywrites=True), 'dm')

In [217]:
Tweets = db['Tweets']
Users = db['Users']

In [218]:
#tablas a pandas DataFrames
tweets = db.Tweets 
users = db.Users
usersDf = pd.DataFrame(list(users.find()))
tweetsDf = pd.DataFrame(list(tweets.find()))

In [219]:
usersDf.head()

,_id,account_created_at,account_lang,description,favourites_count,followers_count,friends_count,listed_count,location,name,...,profile_banner_url,profile_expanded_url,profile_image_url,profile_url,protected,screen_name,statuses_count,url,user_id,verified
0,5b0c128d5987f9243000e493,2009-04-21 18:21:44,es,Noticias de LA NACION. Informaci�n confiable y...,1,3116787,227,9979,Argentina,LA NACION,...,https://pbs.twimg.com/profile_banners/33989170...,http://www.lanacion.com.ar,http://pbs.twimg.com/profile_images/6445642999...,http://t.co/Swk4TRMyc9,False,LANACION,278932,http://t.co/Swk4TRMyc9,33989170,True
1,5b0c128d5987f9243000e494,2012-08-01 15:49:35,es,Gobernador de la Provincia de Salta,760,168886,107,317,"Salta, Argentina",Juan Manuel Urtubey,...,https://pbs.twimg.com/profile_banners/73092677...,http://www.juanmanuelurtubey.com,http://pbs.twimg.com/profile_images/4722080500...,https://t.co/Hf5CN3gH9p,False,UrtubeyJM,3140,https://t.co/Hf5CN3gH9p,730926774,True
2,5b0c128d5987f9243000e495,2009-04-21 18:21:44,es,Noticias de LA NACION. Informaci�n confiable y...,1,3116787,227,9979,Argentina,LA NACION,...,https://pbs.twimg.com/profile_banners/33989170...,http://www.lanacion.com.ar,http://pbs.twimg.com/profile_images/6445642999...,http://t.co/Swk4TRMyc9,False,LANACION,278932,http://t.co/Swk4TRMyc9,33989170,True
3,5b0c128d5987f9243000e496,2010-10-03 05:59:25,es,,38390,1622,1863,7,,Lili,...,https://pbs.twimg.com/profile_banners/19804989...,NaN,http://pbs.twimg.com/profile_images/9618446567...,NaN,False,Lililaumas,53460,NaN,198049895,False
4,5b0c128d5987f9243000e497,2011-02-23 12:23:16,es,CONCEJAL '13-'21 FJV-FPV-UC Catolico no profes...,4117,5929,5897,15,Tres Lomas Pcia Bs As,Franco D.M. Dreessen,...,https://pbs.twimg.com/profile_banners/25648035...,http://www.fm3lomasweb.com.ar,http://pbs.twimg.com/profile_images/9858799173...,http://t.co/ymiZBdntb7,False,Francodreessen,21695,http://t.co/ymiZBdntb7,256480358,False

In [220]:
tweetsDf.describe()

       favorite_count        lat        lng  retweet_count
count      600.000000  31.000000  31.000000     600.000000
mean         3.781667 -30.984989 -58.184726       1.741667
std         16.432002  15.507777  11.940571       9.499755
min          0.000000 -37.147576 -68.866687       0.000000
25%          0.000000 -34.784064 -60.454935       0.000000
50%          0.000000 -34.604315 -58.473042       0.000000
75%          2.000000 -32.906742 -58.442643       0.000000
max        297.000000  51.501586   3.661159     169.000000

In [221]:
usersDf.describe()

,favourites_count,followers_count,friends_count,listed_count,statuses_count
count,600.000000,6.000000e+02,600.000000,600.000000,600.000000
mean,13926.063333,4.453593e+04,1525.168333,120.648333,47157.833333
std,34883.080662,2.913202e+05,5931.803864,741.226474,86936.533410
min,0.000000,0.000000e+00,0.000000,0.000000,1.000000
25%,336.500000,1.135000e+02,187.000000,0.000000,3140.000000
50%,3370.500000,6.015000e+02,499.500000,3.000000,13827.500000
75%,13462.000000,2.646500e+03,1297.000000,23.250000,52606.250000
max,442057.000000,3.999948e+06,93387.000000,9979.000000,944671.000000

In [222]:
tweetsDf.describe()

       favorite_count        lat        lng  retweet_count
count      600.000000  31.000000  31.000000     600.000000
mean         3.781667 -30.984989 -58.184726       1.741667
std         16.432002  15.507777  11.940571       9.499755
min          0.000000 -37.147576 -68.866687       0.000000
25%          0.000000 -34.784064 -60.454935       0.000000
50%          0.000000 -34.604315 -58.473042       0.000000
75%          2.000000 -32.906742 -58.442643       0.000000
max        297.000000  51.501586   3.661159     169.000000

In [223]:
#Borro duplicados de los usuarios, sino hace un n contra n y me da más tweets de los que hay
Users = usersDf.drop_duplicates(keep='last')

In [224]:
lleno = pd.merge(tweetsDf, Users,  how='left', left_on=['user_id', 'screen_name'], right_on = ['user_id', 'screen_name'])

In [225]:
lleno.describe()

,favorite_count,lat,lng,retweet_count,favourites_count,followers_count,friends_count,listed_count,statuses_count
count,790.000000,32.000000,32.000000,790.000000,790.000000,7.900000e+02,790.000000,790.000000,790.000000
mean,4.062025,-31.098093,-58.192786,1.962025,14160.387342,8.371505e+04,1797.798734,237.132911,63139.916456
std,16.581632,15.269012,11.746491,9.538586,39691.886494,3.829333e+05,7001.375150,1089.011898,107637.902586
min,0.000000,-37.147576,-68.866687,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000
25%,0.000000,-34.768430,-60.242391,0.000000,179.500000,1.392500e+02,203.000000,0.000000,3285.750000
50%,1.000000,-34.604315,-58.459642,0.000000,2728.500000,9.000000e+02,593.000000,5.000000,19980.000000
75%,2.000000,-32.918442,-58.442643,1.000000,13027.000000,5.437750e+03,1443.750000,40.000000,78025.000000
max,297.000000,51.501586,3.661159,169.000000,442057.000000,3.999948e+06,93387.000000,9979.000000,944671.000000

In [226]:
lleno['cant_menciones'] = lleno['mentions_screen_name'].apply(lambda x: len(x) -1)

In [227]:
lleno['cant_hash'] = lleno['hashtags'].apply(lambda x: len(x) -1)

In [228]:
lleno['suma'] = lleno['retweet_count'] + lleno['favorite_count']

In [229]:
lleno['popular'] = lleno['suma'].apply(lambda x: True if x > 0 else False)

In [230]:
lleno['suma']

0      111
1      111
2      111
3       99
4       99
5      166
6      166
7      166
8        0
9        1
10       0
11       0
12       0
13       1
14       1
15       0
16       0
17       0
18       2
19       6
20       1
21       1
22       0
23       0
24       0
25       1
26       0
27       0
28       0
29       1
      ...
760      0
761      0
762      0
763      3
764      4
765      4
766      5
767      0
768      0
769      0
770     11
771      1
772      0
773      0
774      0
775      1
776      0
777      0
778      0
779      5
780      0
781      0
782      3
783      0
784      0
785      1
786      9
787      0
788      1
789      0
Name: suma, Length: 790, dtype: int64

In [231]:
modelo = lleno.filter(['friends_count', 'followers_count', 'listed_count', 'statuses_count', 'favourites_count', 'verified', 'is_quote', 'is_retweet', 'favorite_count', 'retweet_count', 'cant_hash', 'cant_menciones', 'popular'])

In [232]:
modelo

,friends_count,followers_count,listed_count,statuses_count,favourites_count,verified,is_quote,is_retweet,favorite_count,retweet_count,cant_hash,cant_menciones,popular
0,227,3116787,9979,278932,1,True,False,False,50,61,0,0,True
1,227,3116787,9979,278932,1,True,False,False,50,61,0,0,True
2,227,3116787,9979,278932,1,True,False,False,50,61,0,0,True
3,107,168886,317,3140,760,True,False,False,68,31,0,1,True
4,107,168886,317,3140,760,True,False,False,68,31,0,1,True
5,227,3116787,9979,278932,1,True,False,False,138,28,0,0,True
6,227,3116787,9979,278932,1,True,False,False,138,28,0,0,True
7,227,3116787,9979,278932,1,True,False,False,138,28,0,0,True
8,1863,1622,7,53460,38390,False,False,False,0,0,0,1,False
9,5897,5929,15,21695,4117,False,False,False,1,0,0,0,True
10,468,246,0,1582,1292,False,False,False,0,0,0,0,False
11,611,547241,697,356311,867,False,False,False,0,0,0,0,False
12,611,547241,697,356311,867,False,False,False,0,0,0,0,False
13,611,547241,697,356311,867,False,False,False,1,0,0,0,True
14,611,547241,697,356311,867,False,False,False,1,0,0,0,True
15,1111,294,11,5137,612,False,False,False,0,0,0,2,False
16,1111,294,11,5137,612,False,False,False,0,0,0,2,False
17,289,154,1,3945,17419,False,False,False,0,0,0,0,False
18,1039,2985,46,65049,38358,False,False,False,2,0,0,0,True
19,161,7937,46,153028,115054,False,False,False,5,1,0,0,True
20,500,330,0,5052,3981,False,False,False,1,0,0,3,True
21,241,826,21,143403,111851,False,False,False,1,0,0,0,True
22,128,105,0,5435,3082,False,False,False,0,0,0,1,False
23,128,105,0,5435,3082,False,False,False,0,0,0,1,False
24,176,110,3,2614,488,False,False,False,0,0,0,0,False
25,191,184,0,1992,471,False,False,False,1,0,0,0,True
26,6077,6996,38,168027,57615,False,False,False,0,0,0,0,False
27,6077,6995,38,168027,57615,False,False,False,0,0,0,0,False
28,6077,6995,38,168027,57615,False,False,False,0,0,0,0,False
29,278,9,0,894,68,False,False,False,1,0,0,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,2190,15144,133,86052,5708,True,False,False,0,0,0,0,False
761,103,63,0,1415,4144,False,False,False,0,0,0,0,False
762,499,455,23,18082,3324,False,False,False,0,0,0,0,False
763,1249,1817,9,94651,174469,False,False,False,3,0,0,0,True
764,1396,1334,1,11173,13027,False,False,False,4,0,0,0,True
765,1396,1334,1,11173,13027,False,False,False,4,0,0,0,True
766,253,291,0,5006,10436,False,False,False,3,2,0,0,True
767,177,28,0,568,1391,False,False,False,0,0,0,0,False
768,177,28,0,568,1391,False,False,False,0,0,0,0,False
769,177,28,0,568,1391,False,False,False,0,0,0,0,False
770,1922,2258,3,20186,14047,False,False,False,11,0,0,0,True
771,48,18,0,420,1915,False,False,False,1,0,0,1,True
772,177,28,0,568,1391,False,False,False,0,0,0,0,False
773,177,28,0,568,1391,False,False,False,0,0,0,0,False
774,177,28,0,568,1391,False,False,False,0,0,0,0,False
775,54,13,1,2516,59,False,False,False,1,0,0,0,True
776,177,28,0,568,1391,False,False,False,0,0,0,0,False
777,177,28,0,568,1391,False,False,False,0,0,0,0,False
778,177,28,0,568,1391,False,False,False,0,0,0,0,False
779,474,316,13,37021,3681,False,False,False,5,0,0,1,True
780,118,70,1,2224,1804,False,False,False,0,0,0,1,False
781,0,0,0,1,1,False,False,False,0,0,0,0,False
782,3176,2924,44,144062,68164,False,False,False,2,1,0,0,True
783,516,665,2,10973,8253,False,False,False,0,0,0,0,False
784,828,275,1,4787,36,False,False,False,0,0,0,0,False
785,3830,3815,5,42291,61329,False,False,False,1,0,0,0,True
786,804,2174,46,63608,67788,False,False,False,9,0,0,0,True
787,1854,336,1,8531,223,False,False,False,0,0,0,0,False
788,751,2288,33,106369,56852,False,False,False,1,0,0,0,True
789,578,848,1,27697,21305,False,True,False,0,0,0,0,False

In [233]:
modelo_y = modelo.loc[:,'popular']

In [234]:
modelo_x = modelo.loc[:, 'friends_count':'cant_menciones']
modelo_x

,friends_count,followers_count,listed_count,statuses_count,favourites_count,verified,is_quote,is_retweet,favorite_count,retweet_count,cant_hash,cant_menciones
0,227,3116787,9979,278932,1,True,False,False,50,61,0,0
1,227,3116787,9979,278932,1,True,False,False,50,61,0,0
2,227,3116787,9979,278932,1,True,False,False,50,61,0,0
3,107,168886,317,3140,760,True,False,False,68,31,0,1
4,107,168886,317,3140,760,True,False,False,68,31,0,1
5,227,3116787,9979,278932,1,True,False,False,138,28,0,0
6,227,3116787,9979,278932,1,True,False,False,138,28,0,0
7,227,3116787,9979,278932,1,True,False,False,138,28,0,0
8,1863,1622,7,53460,38390,False,False,False,0,0,0,1
9,5897,5929,15,21695,4117,False,False,False,1,0,0,0
10,468,246,0,1582,1292,False,False,False,0,0,0,0
11,611,547241,697,356311,867,False,False,False,0,0,0,0
12,611,547241,697,356311,867,False,False,False,0,0,0,0
13,611,547241,697,356311,867,False,False,False,1,0,0,0
14,611,547241,697,356311,867,False,False,False,1,0,0,0
15,1111,294,11,5137,612,False,False,False,0,0,0,2
16,1111,294,11,5137,612,False,False,False,0,0,0,2
17,289,154,1,3945,17419,False,False,False,0,0,0,0
18,1039,2985,46,65049,38358,False,False,False,2,0,0,0
19,161,7937,46,153028,115054,False,False,False,5,1,0,0
20,500,330,0,5052,3981,False,False,False,1,0,0,3
21,241,826,21,143403,111851,False,False,False,1,0,0,0
22,128,105,0,5435,3082,False,False,False,0,0,0,1
23,128,105,0,5435,3082,False,False,False,0,0,0,1
24,176,110,3,2614,488,False,False,False,0,0,0,0
25,191,184,0,1992,471,False,False,False,1,0,0,0
26,6077,6996,38,168027,57615,False,False,False,0,0,0,0
27,6077,6995,38,168027,57615,False,False,False,0,0,0,0
28,6077,6995,38,168027,57615,False,False,False,0,0,0,0
29,278,9,0,894,68,False,False,False,1,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
760,2190,15144,133,86052,5708,True,False,False,0,0,0,0
761,103,63,0,1415,4144,False,False,False,0,0,0,0
762,499,455,23,18082,3324,False,False,False,0,0,0,0
763,1249,1817,9,94651,174469,False,False,False,3,0,0,0
764,1396,1334,1,11173,13027,False,False,False,4,0,0,0
765,1396,1334,1,11173,13027,False,False,False,4,0,0,0
766,253,291,0,5006,10436,False,False,False,3,2,0,0
767,177,28,0,568,1391,False,False,False,0,0,0,0
768,177,28,0,568,1391,False,False,False,0,0,0,0
769,177,28,0,568,1391,False,False,False,0,0,0,0
770,1922,2258,3,20186,14047,False,False,False,11,0,0,0
771,48,18,0,420,1915,False,False,False,1,0,0,1
772,177,28,0,568,1391,False,False,False,0,0,0,0
773,177,28,0,568,1391,False,False,False,0,0,0,0
774,177,28,0,568,1391,False,False,False,0,0,0,0
775,54,13,1,2516,59,False,False,False,1,0,0,0
776,177,28,0,568,1391,False,False,False,0,0,0,0
777,177,28,0,568,1391,False,False,False,0,0,0,0
778,177,28,0,568,1391,False,False,False,0,0,0,0
779,474,316,13,37021,3681,False,False,False,5,0,0,1
780,118,70,1,2224,1804,False,False,False,0,0,0,1
781,0,0,0,1,1,False,False,False,0,0,0,0
782,3176,2924,44,144062,68164,False,False,False,2,1,0,0
783,516,665,2,10973,8253,False,False,False,0,0,0,0
784,828,275,1,4787,36,False,False,False,0,0,0,0
785,3830,3815,5,42291,61329,False,False,False,1,0,0,0
786,804,2174,46,63608,67788,False,False,False,9,0,0,0
787,1854,336,1,8531,223,False,False,False,0,0,0,0
788,751,2288,33,106369,56852,False,False,False,1,0,0,0
789,578,848,1,27697,21305,False,True,False,0,0,0,0

In [235]:
X_train, X_test, y_train, y_test = train_test_split(modelo_x, modelo_y, test_size=0.33, random_state=15)

In [236]:
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [237]:
accuracy_score(y_train, clf.predict(X_train))

1.0

In [238]:
predictions = clf.predict(X_test)
accuracy_score(y_test, predictions)

0.9961685823754789

In [239]:
confusion_matrix(y_test, predictions)

array([[124,   0],
       [  1, 136]])

In [240]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)

In [241]:
feature_importances

                  importance
favorite_count      0.640170
retweet_count       0.157709
followers_count     0.081766
statuses_count      0.036867
listed_count        0.026633
favourites_count    0.023357
friends_count       0.020274
cant_menciones      0.008533
cant_hash           0.003219
is_quote            0.001428
verified            0.000044
is_retweet          0.000000

In [242]:
modelo2 = lleno.filter(['friends_count', 'followers_count', 'listed_count', 'statuses_count', 'favourites_count', 'verified', 'is_quote', 'is_retweet', 'favorite_count', 'retweet_count', 'cant_hashtags', 'cant_menciones', 'popular'])

In [243]:
modelo_y2 = modelo2.loc[:,'popular']
modelo_x2 = modelo2.loc[:, 'friends_count':'is_retweet']
X_train2, X_test2, y_train2, y_test2 = train_test_split(modelo_x2, modelo_y2, test_size=0.33, random_state=None)
clf = RandomForestClassifier()
clf.fit(X_train2, y_train2)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [244]:
accuracy_score(y_train2, clf.predict(X_train2))

0.9395085066162571

In [245]:
accuracy_score(y_train2, clf.predict(X_train2))
predictions2 = clf.predict(X_test2)
accuracy_score(y_test2, predictions2)

0.7088122605363985

In [246]:
confusion_matrix(y_test2, predictions2)

array([[86, 36],
       [40, 99]])

In [247]:
feature_importances2 = pd.DataFrame(clf.feature_importances_,
                                   index = X_train2.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)

In [248]:
feature_importances2

                  importance
favourites_count    0.240909
followers_count     0.231574
listed_count        0.169892
statuses_count      0.168159
friends_count       0.165117
verified            0.014309
is_quote            0.010041
is_retweet          0.000000

In [249]:
corpus = ''
for texto in tweetsDf.text:
    corpus += ' ' + texto

In [250]:
from sklearn.decomposition import PCA

In [251]:
pca = PCA(n_components=2)
X= [lleno['retweet_count'],lleno['favorite_count']]
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [252]:
print(pca.explained_variance_ratio_)

[1.00000000e+00 1.16767304e-33]

In [253]:
print(pca.singular_values_)

[2.15730156e+02 7.37176501e-15]

In [254]:
df3 = pd.merge(tweetsDf, Users,  how='left', left_on=['user_id', 'screen_name'], right_on = ['user_id', 'screen_name'])

In [255]:

df3['cant_menciones'] = df3['mentions_screen_name'].apply(lambda x: len(x) -1)
df3['cant_hash'] = df3['hashtags'].apply(lambda x: len(x) -1)
df3['suma'] = df3['retweet_count'] + df3['favorite_count']


popular = []
for i in range(len( df3)): 
    if  df3['retweet_count'][i] >= 4 or df3['favorite_count'][i] >= 2:
        popular.append(True)
    else: 
        popular.append(False)

        
df3['popular'] = popular

In [256]:
df3=df3.filter(['friends_count', 'followers_count', 'listed_count', 'statuses_count', 'favourites_count', 'verified', 'is_quote', 'is_retweet', 'favorite_count', 'retweet_count', 'cant_hash', 'cant_menciones', 'popular'])

In [257]:
modelo_x3 = df3.loc[:, 'friends_count':'is_retweet']
modelo_y3 = df3.loc[:,'popular']
X_train3, X_test3, y_train3, y_test3 = train_test_split(modelo_x3, modelo_y3, test_size=0.33, random_state=None)
clf = RandomForestClassifier()
clf.fit(X_train3, y_train3)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [258]:
accuracy_score(y_train3, clf.predict(X_train3))
predictions3 = clf.predict(X_test3)
accuracy_score(y_test3, predictions3)

0.7662835249042146

In [259]:
feature_importances3 = pd.DataFrame(clf.feature_importances_,
                                   index = X_train3.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)
feature_importances3

                  importance
followers_count     0.243698
listed_count        0.207026
friends_count       0.181849
statuses_count      0.172685
favourites_count    0.168426
is_quote            0.014995
verified            0.011320
is_retweet          0.000000

In [260]:
from sklearn import svm

In [261]:
modelo_x4 = df3.loc[:, 'friends_count':'favourites_count']
modelo_y4 = df3.loc[:,'popular']
X_train4, X_test4, y_train4, y_test4 = train_test_split(modelo_x4, modelo_y4, test_size=0.33, random_state=None)
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train4, y_train4)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [262]:
accuracy_score(y_train4, clf.predict(X_train4))
predictions4 = clf.predict(X_test4)
accuracy_score(y_test4, predictions4)

0.7586206896551724

In [263]:
confusion_matrix(y_test4, predictions4)

array([[171,  11],
       [ 52,  27]])

In [264]:
from sklearn.ensemble import GradientBoostingClassifier

In [265]:
modelo_x5 = df3.loc[:, 'friends_count':'is_retweet']
modelo_y5 = df3.loc[:,'popular']
X_train5, X_test5, y_train5, y_test5 = train_test_split(modelo_x5, modelo_y5, test_size=0.33, random_state=None)
clf5 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0).fit(X_train5, y_train5)

In [266]:
predictions5 = clf5.predict(X_test5)
accuracy_score(y_test5, predictions5)

0.7777777777777778

In [267]:
feature_importances5 = pd.DataFrame(clf5.feature_importances_,
                                   index = X_train5.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)
feature_importances5

                  importance
statuses_count          0.30
favourites_count        0.21
listed_count            0.17
friends_count           0.16
followers_count         0.13
verified                0.03
is_quote                0.00
is_retweet              0.00

In [268]:

corpus = ''
for texto in tweetsDf.text:
    corpus += ' ' + texto

In [269]:
corpus = corpus.split(' ')

In [270]:
import nltk
from nltk.corpus import stopwords
from collections import Counter
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /Users/pneme/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [271]:
contador = []
for palabra in corpus:
    if palabra.lower() not in stopwords.words('spanish'):
        contador.append(palabra.lower())
    
     
    
conteo_palabras = Counter(contador)

In [272]:
conteo_palabras

Counter({'': 217,
         'así': 12,
         'movida': 3,
         'tinelli,': 53,
         'narváez': 5,
         'manes,': 20,
         'jugar': 18,
         'cambiemos': 17,
         'https://t.co/7wexdarwwu': 2,
         'https://t.co/mcavw7rquc': 2,
         'muchas': 3,
         'gracias': 17,
         '@rosarioa': 2,
         'entrevista': 3,
         'diario': 2,
         '@perfilcom,': 2,
         'pueden': 6,
         'leerla': 2,
         'acá:': 2,
         'https://t.co/jzygfezd2s': 2,
         'https://t.co/gecsdqknd6': 2,
         'bailando': 25,
         'sueño': 11,
         '2018:': 1,
         'marcelo': 82,
         'tinelli': 427,
         'contó': 5,
         'comenzará': 1,
         'julio': 1,
         'agosto,': 1,
         'reveló': 1,
         'serie': 1,
         'homenajeará': 1,
         'apertura': 11,
         'https://t.co/grusllpser': 1,
         'https://t.co/w6vob2bvlv': 1,
         '@gustavobruzone': 15,
         '@editdelvalle': 1,
         'ojalá': 2,
         'mismo': 9,
         'destino!!!': 1,
         '@morojazz': 1,
         '(...)': 1,
         'historia': 1,
         'vuelve': 4,
         'repetirse,\xa0\nmi': 1,
         'muñequita': 1,
         'dulce': 1,
         'rubia,\xa0\nel': 1,
         'amor...': 1,
         'misma': 4,
         'lluvia...\n\npor': 1,
         'vuelta': 6,
         '-': 19,
         'enrique': 1,
         'cadícamo\xa0y': 1,
         'j.': 1,
         'pudiera': 1,
         'ser': 42,
         'juana': 9,
         'tremendo': 1,
         'bombón': 1,
         'https://t.co/fmhi7qwnsj': 1,
         '¡qué': 2,
         'cambio!': 1,
         'nuevo': 4,
         'look:': 1,
         'juanita': 20,
         'abandonó': 2,
         'cabellera': 1,
         'castaña,': 1,
         '¡y': 2,
         'apostó': 2,
         'rubio!\n---&gt;': 1,
         'https://t.co/jk3qfvcnqm': 1,
         'https://t.co/w2ryfbetwu': 1,
         '¡querida': 1,
         'tierra!': 1,
         'vacaciones': 1,
         'guillermina': 3,
         'valdés,': 1,
         'lolo': 1,
         'jujuy.\n---&gt;': 1,
         'https://t.co/edhfq3ktcp': 1,
         'https://t.co/4o83ovc00d': 1,
         '@carod2015': 1,
         'va': 35,
         'pasar.': 1,
         'minimo': 1,
         '30%': 1,
         'antiperonismo': 1,
         'duro.': 1,
         '´prestar': 1,
         'atencion': 1,
         "'posible'": 1,
         'armado.': 2,
         'si': 46,
         'suman': 2,
         '@urtubeyjm': 4,
         'mas,': 3,
         'equipo': 2,
         'tecnico': 1,
         'serio': 7,
         'creible,': 1,
         'puede': 13,
         'potente.': 1,
         'urtubey': 19,
         '(1': 1,
         'mandato)': 1,
         '@cuervotinelli': 36,
         'https://t.co/gesynmxfsg': 1,
         '@maxplus92': 1,
         'empezó': 4,
         'campaña': 11,
         'jujuy?': 1,
         'narvaez,': 3,
         'urtubey...': 1,
         'dice': 9,
         'durán': 1,
         'barba': 1,
         'caribe': 1,
         'cinco': 1,
         'gatos': 1,
         'jodan,': 1,
         'trabajo': 3,
         'hecho.': 1,
         'https://t.co/gbqyrtanwb': 1,
         'soñé': 3,
         'besaba': 1,
         'boca,': 1,
         'asco': 3,
         '!!': 7,
         '<f0><u+009f><u+00a4><u+00ae><f0><u+009f><u+00a4><u+00ae>\nojo': 1,
         'quedaba': 1,
         'fascinado': 1,
         'beso,': 1,
         'conste': 1,
         'actas': 1,
         '!!!\nlas': 1,
         'virgo': 1,
         'sabemos': 1,
         'besar': 1,
         'muyyy': 1,
         'bien': 9,
         '!!\neso': 1,
         'pasa,': 1,
         'haberme': 1,
         'bajado': 1,
         'chocolates': 1,
         '@dr_pijotero': 1,
         '@rafaeldidonato1': 1,
         '@gustavochiriff': 1,
         '@elpaisuy': 1,
         'llevado': 2,
         'política': 7,
         'niveles': 1,
         'descaro': 1,
         'descalificar': 1,
         'gente': 19,
         'sufriendo': 1,
         'consecuencias': 2,
         'club': 9,
         'ineptos': 1,
         'boca': 1,
         'grande': 4,
         'colmo': 2,
         'moralizadores': 1,
         'semana': 6,
         'salen': 1,
         'kk,': 1,
         'c': 1,
         'operete': 1,
         'cuervo': 4,
         'fijate': 1,
         'q': 68,
         'aumentaron': 1,
         'choclos': 1,
         'jajajajaa': 1,
         '@homosapiens2323': 3,
         '@88lamaga': 1,
         'echarri': 16,
         'juntos': 1,
         '2x1?': 1,
         'pobreza': 1,
         'intelectual!!': 1,
         'creen': 3,
         'macri': 12,
         'presidente': 29,
         'boca...cualquiera': 1,
         'puede...': 1,
         'jajaja..pero': 1,
         'olvidaron': 1,
         '8': 1,
         'años': 11,
         'gestión': 1,
         'exitosa': 1,
         'c.a.b.a.': 1,
         'candidato...': 1,
         'gana': 1,
         '1ra': 1,
         'x': 24,
         'mas': 16,
         '25': 1,
         'puntos': 3,
         'futuro': 3,
         'postular': 2,
         '@scabettu': 1,
         'millones': 2,
         'personas': 6,
         'siguen': 1,
         'conductor,': 1,
         'significa': 2,
         'traspolar': 1,
         'activo': 1,
         'directamente': 1,
         'y,': 1,
         'además': 2,
         'depende': 1,
         'partido': 7,
         'vaya': 5,
         'condiciones': 1,
         '@losangeles_ok': 1,
         '@rocioroblesok': 1,
         '@santigriffo': 1,
         '@angeldebritook': 17,
         'uh!': 1,
         'llame': 2,
         'tinelli.': 19,
         'mismo.': 2,
         'aburren.': 1,
         'ir': 7,
         'paso': 9,
         'mago': 2,
         'dientes.': 2,
         'pasada': 1,
         'visitada': 1,
         'provocando': 1,
         'admiración': 1,
         'total': 1,
         'conductor.': 1,
         'fin': 3,
         'largo,': 1,
         'vio': 1,
         'repleta': 1,
         'visitantes': 1,
         'disfrutaron': 1,
         'paisajes.': 1,
         '\n\n¿pudiste': 1,
         'visitarla': 1,
         'semana?\n\nhttps://t.co/zytfxq83lq': 1,
         'https://t.co/g5j8vvhz0h': 1,
         '2)': 2,
         'últimos': 2,
         'años,': 1,
         'empresa': 3,
         '“periodistas”': 2,
         'hicieron': 2,
         'mierda': 8,
         'radio': 7,
         'terminó': 2,
         'repetidora': 1,
         'u': 2,
         'básica.': 1,
         'emisora': 2,
         'supo': 2,
         'tener': 13,
         'rodari,': 2,
         'badia,': 2,
         'mancilla': 3,
         '“modart': 1,
         'noche”': 1,
         'hoy': 9,
         'leopoldo': 2,
         'moreau': 3,
         'programa': 21,
         '#radiodelplata': 2,
         'pasó': 7,
         'casi': 8,
         'vocero': 6,
         'criticarlo': 6,
         'fuerte:': 2,
         '¿qué': 4,
         'pasó?': 2,
         'https://t.co/lcotrolvie': 3,
         '@kmacandall': 1,
         '@lety13ok': 1,
         'narvaez': 3,
         'gran': 15,
         'chanta,': 1,
         'chanta': 1,
         'manes': 15,
         'cree': 3,
         'mejor': 8,
         'mundo,soberbio': 1,
         'ego': 1,
         'da': 11,
         'asco.': 1,
         'candidatos': 6,
         'oposicion': 1,
         '2019': 8,
         '(hasta': 2,
         'ahora)\n1.': 2,
         'massa\n2.': 2,
         'urtubey\n3.': 2,
         'felipe': 4,
         'sola\n4.': 1,
         'agustin': 2,
         'rossi\n5.': 1,
         'mona': 2,
         'gimenez\n6.': 1,
         'tinelli\n7.': 1,
         'milei': 2,
         'espert\n8.': 1,
         'amigos': 2,
         'pasarse': 1,
         'factura': 1,
         'redes': 3,
         'https://t.co/mvgsliinrj': 4,
         '@luisnovaresio': 10,
         'fantino,': 2,
         'vos..@luisnovaresio': 1,
         'jujuy': 9,
         'hace': 12,
         'videoclip': 1,
         'emotivo.': 1,
         'humildad': 3,
         'ambición': 2,
         'hdp': 2,
         '?': 4,
         '\nser': 1,
         '<f0><u+009f><u+0092><u+0080><f0><u+009f><u+00a4><u+0094>': 1,
         'cosas': 2,
         'dicen': 2,
         'el\nbailando': 1,
         '..': 1,
         'favor': 4,
         '<f0><u+009f><u+0091><u+008e><f0><u+009f><u+0091><u+008e><f0><u+009f><u+0091><u+008e>': 1,
         'denigrante': 1,
         '\nestá': 1,
         'rocío': 1,
         '<f0><u+009f><u+0091><u+008e>no': 1,
         '\nmás': 1,
         '<f0><u+009f><u+0091><u+008e>..es': 1,
         'peor\nseguro': 1,
         'entrar': 4,
         '\ntoda': 1,
         'basura': 2,
         '\ntermina': 1,
         'parecería': 2,
         'mal': 12,
         '.lo': 1,
         'jodido': 1,
         'quisiera': 1,
         'presidente.': 6,
         'https://t.co/nigp83r34x': 1,
         '@rialjorge': 1,
         '@intrusos': 1,
         'suena': 1,
         'chica': 2,
         'vamos': 5,
         'ver': 14,
         'proximo': 1,
         'mes!': 1,
         'ohhh': 1,
         'casulidad...': 1,
         'sale': 4,
         'reconciliacion!!!': 1,
         '@gerarfernandez': 2,
         '@radiodelplata': 2,
         'bueno': 4,
         'querido,': 1,
         'cambiaron': 1,
         ',': 18,
         'badia': 1,
         'tantos': 2,
         'históricos': 1,
         'cocineros': 1,
         'argentinos,': 1,
         'marley,': 2,
         'football,': 1,
         'rial,': 4,
         'https://t.co/vyvct22n5i': 1,
         'encima': 3,
         'estan': 1,
         'inflando': 1,
         'candidato,a': 1,
         'tinelli,que': 1,
         'pagarle': 1,
         'empleados': 2,
         'ideas': 2,
         'sur': 2,
         'dejó': 3,
         'calle.': 1,
         'cuadrazo.': 1,
         'acá': 2,
         'aburrida,': 1,
         'trabajando,': 1,
         'pensé': 1,
         'nunca': 11,
         'iba': 3,
         'tocar.': 1,
         'momento': 3,
         'hija': 8,
         'capaz': 2,
         '<f0><u+009f><u+00a4><u+00b7><f0><u+009f><u+008f><u+00bb><u+200d><u+2640><u+fe0f>': 1,
         '@lanacion': 17,
         'vende': 3,
         'patria': 1,
         'extraña': 1,
         '#lazetaentulunesradial': 1,
         'creo': 13,
         'hombre': 1,
         'maletin': 1,
         'dejo': 6,
         'caer': 3,
         'arquero': 1,
         'liverpool....realmente': 1,
         'joda': 11,
         'video': 8,
         'march': 1,
         'viejos': 2,
         'tiempos': 1,
         '@jnunezlazcano': 1,
         '@rodrigosonidom': 1,
         'facundo': 3,
         '2019,': 3,
         'nuevos': 1,
         'integrantes': 1,
         'isis.': 1,
         'todo.': 2,
         'tranqui': 1,
         'dentro': 3,
         '2': 4,
         '3': 3,
         'vas': 5,
         'pidiendo': 2,
         'cámara': 1,
         'tribuna': 1,
         'https://t.co/aypi5i1m2w': 1,
         'supuestos': 1,
         'peronismo': 3,
         '2019:\nagustín': 1,
         'rossi': 1,
         'candidato': 19,
         'presidente.\npablo': 1,
         'jefe': 14,
         'gobierno.\nmarcelo': 1,
         'gobernador': 3,
         'provincia': 3,
         'buenos': 3,
         'aires.\n\nbonus': 1,
         'trak:': 1,
         'solá': 1,
         'kirchnerismo': 1,
         'https://t.co/aykw6s9xvy': 1,
         'problema': 2,
         'argentina': 7,
         'argentinos...': 1,
         'razón': 2,
         'don': 2,
         'jacinto': 1,
         'benavente': 1,
         'premio': 9,
         'nobel': 1,
         'literatura...': 1,
         '"la': 2,
         'única': 3,
         'palabra': 3,
         'formar': 1,
         'argentinos': 5,
         'es:': 1,
         'ignorantes".': 1,
         'cambiar...\nsigan': 1,
         'hizo': 9,
         'votar': 2,
         'alica': 1,
         'alicat': 1,
         'parecido': 1,
         'entente': 1,
         '"de': 1,
         'narváez,': 16,
         'manes"': 1,
         'llega': 4,
         'prosperar,': 1,
         'voy': 6,
         'zambia': 1,
         'baby.': 1,
         'tambien': 5,
         'dueño.': 1,
         'socio': 6,
         'memoria.': 2,
         'periodistas': 3,
         'callan': 2,
         'tinelli?': 14,
         'papeles': 1,
         '¿y': 2,
         'después': 6,
         'tanta': 2,
         'parafernalia,': 1,
         'invitados': 1,
         'especiales': 1,
         're': 5,
         'lanzamiento': 3,
         'néstor': 1,
         'cristina,': 2,
         'sentados': 1,
         'primera': 4,
         'fila': 1,
         'izquierda': 3,
         'punta': 1,
         'banco,': 1,
         'vende?\nvos': 1,
         'tenés': 4,
         'conocimientos': 1,
         'memoria': 2,
         'yo...': 1,
         'tul????': 1,
         'ira': 1,
         'ducote,': 1,
         'ex': 4,
         'ellos?': 1,
         'trío': 15,
         '"enojados"': 14,
         'coqueteó': 14,
         'https://t.co/azbx1zqeha': 1,
         'vía': 11,
         '"ale,': 1,
         'cerebro': 1,
         'crisis,': 1,
         'empieza': 1,
         'pensar': 3,
         'salvoconducto': 1,
         'solucione': 1,
         'problemas': 2,
         'rápidamente.': 1,
         'ejemplo': 1,
         'formula': 3,
         'tinelli-manes': 1,
         '2019"': 1,
         'https://t.co/wzeemexv76': 1,
         'volver': 4,
         'estudiar': 3,
         'https://t.co/dk4cfj24vr': 2,
         '#salta': 2,
         'via': 5,
         '@iruyacom': 2,
         'preguntabas': 1,
         'venía': 1,
         'amor': 3,
         'pibes': 1,
         'puna?\nacá': 1,
         'respuesta.....': 1,
         'https://t.co/edahjqvt2y': 1,
         '#espectáculos\n#tinellienjujuy': 1,
         '#agradecido\nluego': 1,
         'pasar': 1,
         'provincia,': 1,
         'agradeció': 1,
         'instagram': 3,
         'toda': 7,
         'piquete': 16,
         'presentes': 1,
         'primeras': 1,
         'horas': 1,
         'ayer.': 1,
         '\nhttps://t.co/jgkm62vtns': 1,
         'aclaró': 1,
         'morena': 11,
         'rial': 16,
         'convocados': 1,
         '2018': 5,
         'https://t.co/k1okm4h8fa': 1,
         'scioli': 4,
         'vice': 2,
         '.': 4,
         'único': 6,
         'falta': 9,
         'postulen': 1,
         'opositores': 1,
         'futura': 1,
         'elección': 2,
         'van': 9,
         'logar': 1,
         'ponga': 1,
         'algún': 7,
         'compañerito': 1,
         'antonia': 1,
         'ganarles': 1,
         'renovado': 2,
         '2023.': 1,
         'claro': 2,
         'horno.': 1,
         'https://t.co/a7dqwlfe0x': 1,
         'idolatrar': 1,
         'tinelli???': 1,
         'favaaar,': 1,
         'estamos.': 3,
         'ahre': 3,
         '@aleifran': 1,
         '@frataslafraok': 1,
         'avisen???': 1,
         'espera': 1,
         'sentada?': 1,
         'acomodo': 1,
         'medios.': 1,
         'tan': 13,
         'desesperados': 1,
         'empiece': 1,
         'contrario': 1,
         'comen': 1,
         'pasto.': 1,
         'https://t.co/2q2jv7tois': 1,
         'habló': 7,
         'cómo': 19,
         'https://t.co/xc5utvkigs': 1,
         'https://t.co/lqmnua8ucz': 1,
         '...esto': 1,
         'llama': 6,
         'oportunismo......': 1,
         'sabe': 4,
         'ó': 1,
         '$$$$$': 1,
         '@matiaskeeper': 1,
         'vendeles': 1,
         'dólares': 1,
         '$26': 1,
         'seguro': 6,
         'pronostican': 1,
         '$30': 1,
         'yapa': 1,
         'figurita': 1,
         'echarri/tinelli': 1,
         'https://t.co/cwduceujx3': 1,
         '@orwellgeorge': 4,
         'parte': 2,
         'sorprende.': 1,
         'ahora,': 2,
         'parece': 7,
         'pifió': 1,
         'inicio.': 1,
         'quiso': 2,
         'política,': 3,
         'pisando': 1,
         'fuerte,': 2,
         'sumido': 1,
         'irrelevancia.': 1,
         'dio': 14,
         'fuerte': 3,
         'redes..mira': 1,
         'puso': 2,
         'https://t.co/co4dv6eoym': 1,
         'kiiiii': 1,
         'narvaez?': 1,
         'buee...ojala': 1,
         'pueblo': 3,
         'tonto': 1,
         '@felicindacluney': 1,
         'renovacion': 1,
         '2019:\n': 1,
         'tinelli\n': 1,
         'rossi\n': 1,
         'sola\ny': 1,
         'agregar': 1,
         'siempre:\n': 1,
         'massa\n': 1,
         'urtubey\n': 1,
         'randazzo\n': 1,
         'rodriguez': 1,
         'saa\ny': 1,
         'algun': 3,
         'iluminado...\n<f0><u+009f><u+0098><u+00ad><f0><u+009f><u+0098><u+00ad><f0><u+009f><u+0098><u+00ad>': 1,
         '@paulitachaves': 1,
         'a..': 1,
         'braguetera': 1,
         'tinelli....y': 1,
         'ahora': 23,
         'bragueta': 1,
         'prendió': 1,
         'programita....y': 1,
         'amiguita': 1,
         'nara': 1,
         'tenia': 1,
         'ser.': 1,
         'tinelli...?': 1,
         'ahá,': 1,
         'servir...?': 1,
         'https://t.co/3b9xcawzwb': 1,
         '@guida_bor': 1,
         'éste': 3,
         'inelíz': 1,
         'meter': 2,
         'preso!!!': 1,
         'metió': 3,
         'lacra': 1,
         'k': 8,
         'propone': 3,
         'a.presi': 1,
         'tinelli!!<f0><u+009f><u+0098><u+00a3><f0><u+009f><u+0098><u+00a3><f0><u+009f><u+0098><u+009d><f0><u+009f><u+0098><u+00ad><f0><u+009f><u+0098><u+00ab><f0><u+009f><u+0098><u+00ac><f0><u+009f><u+0098><u+00a8><f0><u+009f><u+0092><u+00a9>': 1,
         '@bn_partidos': 1,
         '@escobar_delfi': 1,
         'edionda': 1,
         'canción': 1,
         'menos': 7,
         'ritmo': 1,
         '@mediosyopinion': 1,
         'nombras': 1,
         'eminencia': 1,
         'popo': 1,
         'perro.': 2,
         '@guillevaldes': 1,
         'preocupaciones': 1,
         'señora': 1,
         'tinelli...salga': 1,
         'burbuja': 1,
         'querida...': 1,
         'plata.': 2,
         'dificultad': 1,
         'hacer': 14,
         'medios': 5,
         'kirchneristas': 1,
         'plata': 9,
         'ajena': 2,
         'sindicato': 1,
         'prensa,': 1,
         'políticos': 5,
         'responsables': 1,
         'triste': 1,
         'final\nhttps://t.co/ces1awc3mu\nuna': 1,
         '“modart”': 1,
         'https://t.co/lrf2qapzc0': 1,
         'dije': 5,
         'tengl': 1,
         'compañera': 1,
         'conocía': 1,
         'susana': 2,
         'tinelli?!': 1,
         'mirkoo!!!!!': 1,
         'entienden': 1,
         'indignación?': 1,
         '<f0><u+009f><u+00a4><u+0094>\npor': 1,
         'suerte': 1,
         'one': 1,
         'toma': 1,
         '@orwellgeorge,': 1,
         'empezar': 4,
         'manera': 2,
         'horrible': 2,
         'lunes:\nhttps://t.co/4idhtk9zlj': 1,
         'dijo': 11,
         'ignora': 7,
         '“sistema': 2,
         'republicano”': 1,
         '|': 5,
         'cronica': 1,
         'noa': 1,
         'https://t.co/tdj5nluxup': 1,
         '@marley_ok': 2,
         '@telefe': 2,
         'sos': 12,
         'conductor': 5,
         'pais.': 1,
         'existe': 1,
         'lado': 3,
         'tuyo.': 1,
         '#marcelotinelli': 1,
         'persona': 4,
         'cumplió': 7,
         '#elpiquete\nhttps://t.co/cvmhvukxhe': 1,
         '@gury_2018': 2,
         '@soylistorti': 3,
         'xq': 9,
         'listorti': 5,
         'tinelli,eso': 1,
         'plata,de': 1,
         'obligación': 3,
         'sentir': 2,
         'humano': 1,
         '¿guerra': 6,
         'posibles': 6,
         'candidatos?': 6,
         '"sistema': 5,
         'republicano"': 6,
         'https://t.co/smrnrfcvx4': 2,
         'https://t.co/oktquz25jd': 1,
         'presentación': 2,
         'basada': 2,
         'casa': 8,
         'papel.': 1,
         'poder': 3,
         'resistir': 1,
         'creatividad': 1,
         'infinita': 1,
         'cerebro?': 1,
         'preparan': 2,
         'sorpresa': 2,
         'adelantó': 5,
         '#bailando2018.': 1,